version: "3.8"

services:
  mysql:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: nestjs-graphql
      # MYSQL_USER: root
      # MYSQL_PASSWORD: 12345
    volumes:
      - ./data:/var/lib/mysql
  backend:
    container_name: nestjs-graphql
    image: nestjs_graphql_api
    build: .
    ports:
      - "8000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - mysql
    environment:
      HOST: 0.0.0.0
    volumes:
      - ./:/src
networks:
  default:
    external:
      name: 'baonetwork'
