version: "3.5"

services:
  mysql:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: nestjs-graphql
      # MYSQL_USER: root
      # MYSQL_PASSWORD: 12345
    volumes:
      - ./data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    volumes:
      - ./data:/var/lib/mysql
  backend:
    container_name: nestjs-graphql
    image: nestjs_graphql_api
    build: .
    ports:
      - "8000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - mysql
      - phpmyadmin
    environment:
      HOST: 0.0.0.0
